"""Phase 10 Intelligence baseline

Revision ID: 04fa4cfd1e8c
Revises: 
Create Date: 2026-02-26 15:07:41.222678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '04fa4cfd1e8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('agent_id', app.models.GUID(length=32), nullable=True))
    op.add_column('campaigns', sa.Column('called', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('conversions', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('ab_variants', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_campaigns_channel'), 'campaigns', ['channel'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.drop_column('campaigns', 'completed_contacts')
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.add_column('voice_agents', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('voice_agents', sa.Column('sip_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_agents', 'sip_config')
    op.drop_column('voice_agents', 'provider')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.add_column('campaigns', sa.Column('completed_contacts', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_channel'), table_name='campaigns')
    op.drop_column('campaigns', 'scheduled_at')
    op.drop_column('campaigns', 'ab_variants')
    op.drop_column('campaigns', 'conversions')
    op.drop_column('campaigns', 'called')
    op.drop_column('campaigns', 'agent_id')
    # ### end Alembic commands ###
